export type StorefrontLayoutId = 'classic' | 'minimal' | 'compact' | 'creative' | 'editorial';

export type SectionType =
    | 'hero'
    | 'features'
    | 'rich-text'
    | 'gallery'
    | 'contact'
    | 'product-showcase'
    | 'cta-banner'
    | 'faq'
    | 'testimonial';

export interface SectionContent {
    heading?: string;
    subheading?: string;
    text?: string;
    primaryAction?: { label: string; href: string };
    secondaryAction?: { label: string; href: string };
    items?: any[];
    images?: { url: string; alt?: string }[];
    [key: string]: any;
}

export interface SectionSettings {
    backgroundColor?: string;
    textColor?: string;
    padding?: 'none' | 'small' | 'medium' | 'large';
    isVisible?: boolean;
    aiSuggested?: boolean; // Label for sections generated by AI
    layoutVariation?: string; // Variation within a section type
}

export interface StorefrontSection {
    id: string;
    type: SectionType;
    content: SectionContent;
    settings: SectionSettings;
}

export interface StorefrontPage {
    id: string;
    title: string;
    slug: string;
    status: 'Published' | 'Draft';
    sections: StorefrontSection[];
    meta?: {
        title?: string;
        description?: string;
        ogImage?: string;
    };
    isHome: boolean;
    updatedAt: string;
}

export interface StorefrontConfig {
    theme: {
        layout: StorefrontLayoutId;
        primaryColor: string;
        fontHeading: string;
        fontBody: string;
        logoUrl?: string;
    };
    navigation: {
        header: { label: string; href: string }[];
        footer: { label: string; href: string }[];
    };
}
