export enum Permission {
    // Financial
    VIEW_FINANCIALS = 'VIEW_FINANCIALS',

    // Sales
    VIEW_SALES = 'VIEW_SALES',
    RECORD_SALE = 'RECORD_SALE',
    UPDATE_SALE = 'UPDATE_SALE',
    DELETE_SALE = 'DELETE_SALE',

    // Products
    MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',

    // Customers
    VIEW_CUSTOMERS = 'VIEW_CUSTOMERS',
    UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER = 'DELETE_CUSTOMER',

    // Suppliers & Payables
    VIEW_SUPPLIERS = 'VIEW_SUPPLIERS',
    MANAGE_SUPPLIERS = 'MANAGE_SUPPLIERS',
    RECORD_PAYABLE = 'RECORD_PAYABLE',
    PAY_SUPPLIER = 'PAY_SUPPLIER',

    // Staff
    VIEW_STAFF = 'VIEW_STAFF',
    MANAGE_STAFF = 'MANAGE_STAFF',

    // Expenses
    RECORD_EXPENSE = 'RECORD_EXPENSE',
    VIEW_EXPENSES = 'VIEW_EXPENSES',

    // Debts (customer owes you)
    RECORD_REPAYMENT = 'RECORD_REPAYMENT',

    // Subscription
    MANAGE_SUBSCRIPTION = 'MANAGE_SUBSCRIPTION',

    // Payouts
    MANAGE_PAYOUTS = 'MANAGE_PAYOUTS',

    // General
    VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    VIEW_PRODUCTS = 'VIEW_PRODUCTS',
    CREATE_CUSTOMER = 'CREATE_CUSTOMER',
    VIEW_STORES = 'VIEW_STORES',
    MANAGE_STORES = 'MANAGE_STORES',
    MANAGE_BUSINESS_CONFIG = 'MANAGE_BUSINESS_CONFIG',

    // School preset
    VIEW_ACADEMIC_CALENDAR = 'VIEW_ACADEMIC_CALENDAR',
    MANAGE_ACADEMIC_CALENDAR = 'MANAGE_ACADEMIC_CALENDAR',
    VIEW_FEE_TEMPLATES = 'VIEW_FEE_TEMPLATES',
    MANAGE_FEE_TEMPLATES = 'MANAGE_FEE_TEMPLATES',

    // Restaurant preset
    VIEW_RESTAURANT_TABLES = 'VIEW_RESTAURANT_TABLES',
    MANAGE_RESTAURANT_TABLES = 'MANAGE_RESTAURANT_TABLES',
    VIEW_KITCHEN_TICKETS = 'VIEW_KITCHEN_TICKETS',
    MANAGE_KITCHEN_TICKETS = 'MANAGE_KITCHEN_TICKETS',
    VIEW_BAR_TICKETS = 'VIEW_BAR_TICKETS',
    MANAGE_BAR_TICKETS = 'MANAGE_BAR_TICKETS',
}
